function [data, data_spec, data_single_spec] = load_data(prefix)
    data = [load_ball_data(prefix + "data_1e-2.txt")];
    data(end+1) = load_ball_data("data_7.5e-3.txt");
    data(end+1) = load_ball_data("data_5e-3.txt");
    data(end+1) = load_ball_data("data_2.5e-3.txt");
    data(end+1) = load_ball_data("data_1e-3.txt");
    data(end+1) = load_ball_data("data_5e-4.txt");
    data(end+1) = load_ball_data("data_1e-4.txt");
    data(end+1) = load_ball_data("data_1e-5.txt");
    data_spec = [load_ball_data("data_spec_1e-2.txt")];
    data_spec(end+1) = load_ball_data("data_spec_7.5e-3.txt");
    data_spec(end+1) = load_ball_data("data_spec_5e-3.txt");
    data_spec(end+1) = load_ball_data("data_spec_2.5e-3.txt");
    data_spec(end+1) = load_ball_data("data_spec_1e-3.txt");
    data_spec(end+1) = load_ball_data("data_spec_5e-4.txt");
    data_spec(end+1) = load_ball_data("data_spec_1e-4.txt");
    data_spec(end+1) = load_ball_data("data_spec_1e-5.txt");
    data_single_spec = [load_ball_data("data_single_spec_1e-2.txt")];
    data_single_spec(end+1) = load_ball_data("data_single_spec_7.5e-3.txt");
    data_single_spec(end+1) = load_ball_data("data_single_spec_5e-3.txt");
    data_single_spec(end+1) = load_ball_data("data_single_spec_2.5e-3.txt");
    data_single_spec(end+1) = load_ball_data("data_single_spec_1e-3.txt");
    data_single_spec(end+1) = load_ball_data("data_single_spec_5e-4.txt");
    data_single_spec(end+1) = load_ball_data("data_single_spec_1e-4.txt");
    data_single_spec(end+1) = load_ball_data("data_single_spec_1e-5.txt");
end